# Generated by Django 5.2 on 2025-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
